function line_coordinates3D = compute3DCoordinatesLineEndPoints(...
                line_origin,...
                line_direction,...
                line_coordinates2D,...
                P) 

% Compute:            
line_coordinates3D(1,1:3) = ...
    find3DCoordinatesLine(P, line_origin, line_direction, line_coordinates2D([1,3]));
line_coordinates3D(1,4:6) = ...
    find3DCoordinatesLine(P, line_origin, line_direction, line_coordinates2D([2,4]));


%Clip if too long:
% line_coordinates3D(1,4:6) = clip3DLine( line_coordinates3D(1,1:3),...
%                                     line_coordinates3D(1,4:6));
end