% Description:
%   Intialises the structure of the candidate line, given an origin,
%   direction, 2D line primitive coordinates and camera rojection matrix.

function candidate_line = ...
                createOneCandidateLine( origin,...
                                        direction,...
                                        primitive_geom,...
                                        P,...
                                        inds_intrsctns,...
                                        inds_intrsctns__assigned,...
                                        inds_intrsctns__mult_cnddts,...
                                        inds_intrsctns__mult_cnddts_ind,...
                                        inds_jnts_strks,...
                                        p_intrsctns_dists,...
                                        p_directional,...
                                        p_coverage,...
                                        p_full)                                       
                                    
    candidate_line.origin  = origin;
    candidate_line.dir     = direction;        

    candidate_line.coordinates3D_prior = compute3DCoordinatesLineEndPoints(...
                                                        origin,...
                                                        direction,...
                                                        primitive_geom,...
                                                        P); 

    candidate_line.length3D = sqrt(sum( (candidate_line.coordinates3D_prior(1, 4:6) -  ...
                                         candidate_line.coordinates3D_prior(1, 1:3)).^2));

    candidate_line.configurations = [];

    if ~exist('p_intrsctns_dists', 'var')
        p_intrsctns_dists = 1.0;
    end
    if ~exist('p_directional ', 'var')
        p_directional = 1.0;
    end
    if ~exist('p_coverage ', 'var')
        p_coverage = 0.0;
    end
    if ~exist('p_full ', 'var')
        p_full = 1.0;
    end


    candidate_line = addIntersectionsConfigCandidateLine(...
                            candidate_line,...
                            inds_intrsctns,...
                            inds_intrsctns__assigned,...
                            inds_intrsctns__mult_cnddts,...
                            inds_intrsctns__mult_cnddts_ind,...
                            inds_jnts_strks,...                                
                            p_intrsctns_dists,...
                            p_directional,...
                            p_coverage,...
                            p_full);
                    
    candidate_line.list_jnt_strks = [];
end