function candidate_line = initialiseOneCandidateLine(origin,...
                                                 direction,...
                                                 primitive_geom,...
                                                 P)
                                            
candidate_line.origin  = origin;
candidate_line.dir     = direction;        

candidate_line.coordinates3D_prior = compute3DCoordinatesLineEndPoints(...
                                                    origin,...
                                                    direction,...
                                                    primitive_geom,...
                                                    P); 
                              
candidate_line.length3D = sqrt(sum( (candidate_line.coordinates3D_prior(1, 4:6) -  ...
                                      candidate_line.coordinates3D_prior(1, 1:3)).^2));
                                               
candidate_line.configurations = [];

candidate_line.list_jnt_strks = [];

end