function [inds_non_assigned_strks,...
          max_costs, ...
          confidence_vals] = ...
                sortStrokesScoreConfidence(inds_non_assigned_strks,...
                                    max_costs, ...
                                    confidence_vals)

[~, inds] = sortrows([max_costs+confidence_vals],'descend'); 
confidence_vals = confidence_vals(inds);
inds_non_assigned_strks = inds_non_assigned_strks(inds);
max_costs = max_costs(inds);

end