function plotStrokesTopolgyIntersectionsTypes(...
                        strokes_topology,...
                        cur_stroke,...
                        intersections,...
                        fig_num_3D)
    
    strokes_assigned = strokes_topology(cat(1, strokes_topology(:).depth_assigned));
    plotStrokesTopology(fig_num_3D, strokes_assigned);
    
    ic3D = cat(1,intersections.coordinates3D);
      
    %Plot the intersections:
    plot3( ic3D(cur_stroke.inds_intrsctns_eval,1),...
           ic3D(cur_stroke.inds_intrsctns_eval,2),...
           ic3D(cur_stroke.inds_intrsctns_eval,3),...
           '*');
    camlight;   
%     plot3( ic3D(cur_stroke.nodes_indices_active_others,1),...
%            ic3D(cur_stroke.nodes_indices_active_others,2),...
%            ic3D(cur_stroke.nodes_indices_active_others,3),...
%            'bo');
%       
    [x,y,z] = sphere;
    r = 0.01*max(cat(1,strokes_assigned(:).length3D));
    x = x*r;
    y = y*r;
    z = z*r;
    
    for i =1:length(strokes_assigned)
        indices = strokes_assigned(i).indcs_intrsctns;
        indices1 = indices(cat(1,intersections(indices).is_active) == 1 );
                       
%         indices2 = indices(isnan(cat(1,intersections(indices).is_active))& ...
%                            cat(1,intersections(indices).likely) );

        indices3 = indices(cat(1,intersections(indices).is_active) == 0  );
    
        
        for j = 1:length(indices1)
            s = surf(x+ ic3D(indices1(j),1), ...
                 y+ ic3D(indices1(j),2), ...
                 z+ ic3D(indices1(j),3));
            s.EdgeColor = 'none';
            
        end
%         plot3( ic3D(indices1,1),...
%                ic3D(indices1,2),...
%                ic3D(indices1,3),...
%                'go');   
           
%         plot3( ic3D(indices2,1),...
%                ic3D(indices2,2),...
%                ic3D(indices2,3),...
%                'bo');  
           
        plot3( ic3D(indices3,1),...
               ic3D(indices3,2),...
               ic3D(indices3,3),...
               'ro');  
    end
    
    %% Display the number of the intersections:
    a = cur_stroke.inds_intrsctns_eval(:); 
    b = num2str(a); 
    c = cellstr(b);
    text( ic3D(cur_stroke.inds_intrsctns_eval,1),...
          ic3D(cur_stroke.inds_intrsctns_eval,2),...
          ic3D(cur_stroke.inds_intrsctns_eval,3),...
          c, 'FontSize',14);

%     h = figure(fig_num_3D);
    set(gca, 'CameraPosition', [-1.0187 -1.2650 -0.7392]);
    set(gca, 'CameraTarget', [-0.0640 0.1346 0.0024]);
%    set(h, 'Position', [983 45 743 846]);
   
%    saveMP4s(strokes_topology);
   
end

