function [candidate_line_new] = mergeIntoSingleLineWithMultipleConfirations(candidate_lines,...
                                        ind_similar_cand_lines,...
                                        cur_stroke,...
                                        cam_param)

%% Intialize:  
mean_pos = mean(cat(1,candidate_lines(ind_similar_cand_lines).coordinates3D_prior), 1);
mean_dir = mean_pos(4:6) - mean_pos(1:3);
mean_dir = mean_dir./norm(mean_dir);

candidate_line_new = initialiseOneCandidateLine(mean(cat(1,candidate_lines(ind_similar_cand_lines).origin),1),...
                                            mean_dir,...
                                            cur_stroke.primitive_geom,...
                                            cam_param.P);                                  
%% Add all the configurations:

for j = 1:length(ind_similar_cand_lines)
     iscl = ind_similar_cand_lines(j);
     
%      warning('candidate_lines(iscl).configurations(1).p_intrsctns_distances can be updated');
%      
%      plot3(candidate_lines(ind_similar_cand_lines(j)).coordinates3D_prior(1,[1,4]), ...
%           candidate_lines(ind_similar_cand_lines(j)).coordinates3D_prior(1,[2,5]), ...
%           candidate_lines(ind_similar_cand_lines(j)).coordinates3D_prior(1,[3,6]), '*-');
      
     for jj = 1:length(candidate_lines(iscl).configurations)
         candidate_line_new = addIntersectionsConfigCandidateLine(...
                                    candidate_line_new,...
                                    candidate_lines(iscl).configurations(jj).inds_intrsctns,...
                                    candidate_lines(iscl).configurations(jj).inds_intrsctns__assigned,...
                                    candidate_lines(iscl).configurations(jj).inds_intrsctns__mult_cnddts,...
                                    candidate_lines(iscl).configurations(jj).inds_intrsctns__mult_cnddts_ind, ...
                                    candidate_lines(iscl).configurations(jj).inds_jnts_strks,...                                        
                                    candidate_lines(iscl).configurations(jj).p_intrsctns_dists,...
                                    NaN,...
                                    NaN,...
                                    NaN);                                            
     end
end
